### ISSUE TITLE
LAzyObject Is missing the keySet function

### ISSUE THREAD

**Issue by jtwebman** [doubledutch/LazyJSON#11]
This is just a nice to have as the keySet function lets you use a Java foreach instead of having to use the keys that returns an iterator. Here is the referense to it fro mthe json.org library.

https://stleary.github.io/JSON-java/org/json/JSONObject.html#keySet--

**Comment by jtwebman** [comment]
Did you not see my Slack message? Why did you close it?

**Comment by kasperjj** [comment]
fixed in v1.2.5
