### ISSUE TITLE
Is it possible to implement a #hashCode() and #equals methods for LazyElements? 

### ISSUE THREAD

**Issue by alphahelix00** [doubledutch/LazyJSON#13]
Hey @kasperjj , thanks for the quick update for #12 . I am currently in progress of writing the aforementioned JSON deepEquals comparison [lib](https://github.com/alphahelix00/jsonequals). I'm trying to handle cases for JSON arrays where the responses may come in out of order, e.g. : 

JSON A:
```json
[
    {
        "field1": "value1"
    },
    {
        "field2": "value2"
    }
]
```

JSON B:
```json
[
    {
        "field2": "value2"
    },
    {
        "field1": "value1"
    }
]
```

What I am currently doing is when I am at a JSON array node, I retrieve all the children from JSON A and JSON B and put them into two different `List<LazyElement>`s, but in the example case shown above, I'd like to have a way of sorting the list such that I can compare each child node in order.

I am not sure if this is possible, since in the LazyJSON readme it was mentioned that `the parser will validate the source string when we instantiate the LazyObject class, but it won't actually create an int from the value of the foo field until we request it.`

If not, any recommendations on how to handle this case?

**Comment by alphahelix00** [comment]
One way I was thinking of was to have a hashCode function inside a LazyElement, which would technically require one to request the value of the field. -> request the field value in String form and returning the hashed int code of it.

**Comment by alphahelix00** [comment]
For now, I am doing this and it seems to be working fine:

```java
lazyObjects.sort(Comparator.comparingInt((node) -> (node.keySet() + node.toString()).hashCode()));

lazyArrays.sort(Comparator.comparingInt((node) -> (node.length() + node.toString()).hashCode()));

primitives.sort(Comparator.comparingInt(Object::hashCode));
```

Haven't had a case where this would fail.

**Comment by kasperjj** [comment]
yeah, I think the key / index concatenated with the content of the node will work well until you start getting hashcode clashes :-) ...at that point, it could be a very annoying bug to uncover for whomever is using the lib :-)

**Comment by alphahelix00** [comment]
Wow, looks like I had a huge mental lapse and forgot that JSON arrays are ordered, so things like ordering in JSON arrays shouldn't be considered. My apologies.

I mistakenly thought I was dealing with unordered field names in a JSON object, but that's already been covered since they're stored in Sets.

**Comment by kasperjj** [comment]
Hey, I added a new equals method that does deep inspections and answers true to JSON data that is semantically equal. The hashcode method has also been updated to reflect the same semantic equality guarantee. Compared to the hashcode approach, this will consider two JSON data structures equal, even if they are formatted differently.

**Comment by alphahelix00** [comment]
Hey Kasper, thanks for the update.
However, in the case with my lib I have a selective deep equality check. In JSON objects, some fields can be chosen to be [ignored](https://github.com/alphahelix00/jsonequals#ignoring-json-fields) from comparison (e.g. timestamp values in a response), and in JSON arrays, some array elements can [removed](https://github.com/alphahelix00/jsonequals#pruning-json-arrays) from the array from comparison depending on the values of the inner array objects (e.g. if the inner array object has a field named "someBoolean" with value "false", then I remove this element from the array prior to comparison).

So, I decided to not use hashCode at all, because I am not sorting the arrays anymore. Nevertheless, my deep equals check is similar to your implementation in the same mindset of traversing the JSON tree and checking for inequalities, just that for mine I have extra conditional statements for ignoring fields or pruning arrays.
