### ISSUE TITLE
LazyArray toString produces invalid json

### ISSUE THREAD

**Issue by sacha-cs** [doubledutch/LazyJSON#17]
Calling `toString` on a `LazyArray` produces invalid JSON when one of the string values in the array contains escaped characters (e.g. double quotes).

Here is an example test that is failing:
```
@Test
    public void testSerializeStringWithEscapedQuotes() {
        LazyArray lazyArray = new LazyArray();
        lazyArray.put("\"foo\" bar");
        lazyArray.put("baz");
        assertEquals("[\"\\\"foo\\\" bar\",\"baz\"]", lazyArray.toString());
    }
```

Result:
```
Expected :["\"foo\" bar","baz"]
Actual   :[""foo" bar","baz"]
```

**Comment by kasperjj** [comment]
Thanks for the thorough pull request on this! I have merged your pull request and pushed a new release to maven central.

**Comment by sacha-cs** [comment]
Thanks 👍
